Story8/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.data, name='ambil_data'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json

def home(request):
    return render(request, 'main/home.html')
def data(request):
    arg = request.GET['q']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(url_tujuan)

    data = json.loads(r.content)
    return JsonResponse(data,safe=False)

main/templates/main/home.html
{% load static %}
<html>
    <head>
        <title>
            Book Search     
        </title>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <script>
            const data_books_url = "{% url 'main:ambil_data' %}?q=";
        </script>
    </head>
    <body>
        <div class="container">
            <div class="judul pt-3 text-center mb-3">Book Search</div>
            <div class="row">
                <input type="text" placeholder="Search for you favorite book here" title="Type in the title" class="align-items-center" name="search_box">
                <button type="button" id="input" class="btn btn-grad" name="search_submit">Search</button>
            </div>
            <table class="table mt-5">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="align-middle">No</th>
                    <th scope="col" class="align-middle">Book Cover</th>
                    <th scope="col" class="align-middle">Title</th>
                    <th scope="col" class="align-middle">Authors</th>
                    <th scope="col" class="align-middle">Publisher</th>
                   
                  </tr>
                </thead>
                <tbody id="konten"></tbody>
            </table>
            
        </div>
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>